# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeb5bc2f3ab12d6c215fc4a4e6c400b1254533d4e7e136dec7f3b63261ccc8d915e7d2f8d75bbcab7ba944e3a25334c8ada063b824fdd66967d9d815c426e07b

test:
  secret_key_base: 2c1923e6992ecf21c05548e4ec66616f98f0ae27b28a085aeac6cf71e17f7cdf40e6ef2444da9369abf552faffd4243e6c483248bbd35d0f935b8e95c73a3835

staging:
  secret_key_base: <%= ENV["secret_token"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_token"] %>

